version: '3'

services:
  app:
    image: beidongjiedeguang/chatgpt-web:latest
    ports:
      - 21567:3002
    environment:
      # 二选一
      OPENAI_API_KEY: kunyuan :)
      # 二选一
      # OPENAI_ACCESS_TOKEN: xxx
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      # OPENAI_API_BASE_URL: https://api.openai.com
      # OPENAI_API_BASE_URL: http://198.211.51.254:8000/openai
      OPENAI_API_BASE_URL: http://2.56.125.247:8000/openai
      
      # API模型，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_MODEL: "gpt-3.5-turbo"
      # 反向代理，可选
      # API_REVERSE_PROXY: xxx
      # 访问权限密钥，可选
      # AUTH_SECRET_KEY: xxx
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 60000
      # Socks代理，可选，和 SOCKS_PROXY_PORT 一起时生效
      # SOCKS_PROXY_HOST: xxx
      # Socks代理端口，可选，和 SOCKS_PROXY_HOST 一起时生效
      # SOCKS_PROXY_PORT: xxx
      # HTTPS 代理，可选，支持 http，https，socks5
      # HTTPS_PROXY: http://localhost:7890

